defaults:
  job: &job-defaults
    docker:
      - image: docker:18.05
    steps:
      - checkout
      - setup_remote_docker
      - run: ${BUILD_COMMAND}
      - deploy:
          name: Push Docker image
          command: |
            if [ ! -z "${DOCKERHUB_USER}" ]; then
              docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
              docker push $(docker images --format '{{.Repository}}' 'thunderatz/*')
            else
              echo Docker credentials not found
            fi
      - run:
          name: Save Docker image artifact
          command: |
            mkdir -p /tmp/artifacts
            docker save -o /tmp/artifacts/image.tar $(docker images --format '{{.Repository}}' 'thunderatz/*')
      - store_artifacts:
          path: /tmp/artifacts/image.tar
          destination: image.tar
version: 2
jobs:
  build:
    <<: *job-defaults
    environment:
      BUILD_COMMAND: "./build.sh"
  build-cuda:
    <<: *job-defaults
    environment:
      BUILD_COMMAND: "docker build -t thunderatz/ros-base-cuda --build-arg base_image=nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 docker/"
workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - build-cuda
