version: 2
jobs:
  build: &default-build
    docker:
      - image: docker:18.05
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh
  build-cuda:
    <<: *default-build
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build-cuda.sh
workflows:
  version: 2
  build-all:
    jobs:
      - build
      - build-cuda
