version: 2
jobs:
  build:
    docker:
      - image: docker:18.05
    working_directory: ~/ros-base
    steps:
      - checkout
      - setup_remote_docker
      - run: sh ./build.sh
  build-cuda:
    docker:
      - image: docker:18.05
    working_directory: ~/ros-base
    steps:
      - checkout
      - setup_remote_docker
      - run: sh ./build-cuda.sh
workflows:
  version: 2
  build-all:
    jobs:
      - build
      - build-cuda
